### ISSUE TITLE
Feature Request: truncated identifiers

### ISSUE THREAD

**Issue by oliverkane** [dalibo/sqlserver2pgsql#159]
This script is almost perfect for my needs. I'm using Entity Framework for a medium/large application and we have a great many auto-generated FK identifiers which are extremely long.  Would you consider adding in a flag which would truncate Identifiers above say 63 characters for FK constraints to something perhaps 58 characters, with the remaining a random string?

[AWS's Schema Conversion Tool ](https://docs.aws.amazon.com/SchemaConversionTool/latest/userguide/CHAP_Welcome.html) has this feature, however, it does a much worse job at the rest of the translation.  

If this is something you'd be willing to add, I can try to figure out if I can learn enough perl regex to make it work.  I don't know perl at all yet, but this would be super helpful if I could add it.

For now, there's only like 200 entries on current project so it's about a wash in terms of just doing this manually.

**Comment by oliverkane** [comment]
Basically here's what I'm doing to resolve it now in the output scripts.  I think at worst case, I can do this as a post-processing step.

![image](https://user-images.githubusercontent.com/1761622/125199723-37a68e00-e22d-11eb-86f6-09fcc251b239.png)

**Comment by beaud76** [comment]
I understand the point, which is related to potentially all identifiers (tables, columns, constraints, etc), because Postgres identifier names are limited to 63 (unless recompiling the code) while the same limit equals 128 with SQL-Server. 

If this happens with tables and columns, there is nothing to do but renaming them in the creation script and in all the clients, which is a big deal. In this case, the CREATE TABLE statement generated by sqlserver2pgsql will just fail, requiring manual changes.

On the contrary, changing a constraint name has generally no impact on applications or tools. So your proposal is valid. But there is another way to tackle the issue: let Postgres compute the constraint name by not providing the constraint name in the ALTER TABLE statement. The constraint name is built using a combination of table name, column names and constraint type. And it properly manages duplicate names. The advantage of this approach is that the re-runing sqlserver2pgsql several times with the same input dump will always generate the same output. This stability is not only helpful for the user but also for non regression tests.

So I plan to add a piece of code that erases the constraint name when the source constraint name length is greater than 63.

**Comment by beaud76** [comment]
Done in commit 0f9e080738b595ba69632a6f01a99a181aa7cecd.

**Comment by oliverkane** [comment]
@beaud76, that's awesome!  I didn't know about that feature in pgsql.  I'm slowly warming to it after getting over my ptsd with SQL Server and all the fun licensing there.

Do you accept crypto tips?  Can't much pay you a full wage, but I would like to express a bit of gratitude if possible.

**Comment by oliverkane** [comment]
This works flawlessly. Thanks again!

**Comment by beaud76** [comment]
@oliverkane, it's nice to known that it works well. I do not accept crypto tips. My employeer pays me enough, also to participate to open source development ;-). The best way to thank me is to promote PostgreSQL and the good work done by its community.
