### ISSUE TITLE
Incremental kettle script fails for columns of type smallmoney

### ISSUE THREAD

**Issue by JCallico** [dalibo/sqlserver2pgsql#46]
Got the following error from the incremental kettle script:

> The data type of field #8 is not the same as the first row received: you're mixing rows with different layout. Field [Column1 BigNumber] does not have the same data type as field [Column1 Number(10, 4)].

The original column in T-SQL is defined as:

`[Column1] [smallmoney] NULL,`

The "before" PostgreSQL script defined it as:

`"Column1" numeric,`

Before I add another custom conversion, I'm wondering if numeric is the correct data type to use for smallmoney?

**Comment by marco44** [comment]
Numeric is the correct data type. But we should add a precision to make it happy, probably…

If it's the smallmoney that is mapped to number(10,4):

From what I understand here, https://technet.microsoft.com/en-us/library/ms179882(v=sql.110).aspx

smallmoney should be numeric(6,4) and money numeric(15,4)...

What's funny is that according to Microsoft (https://msdn.microsoft.com/en-us/library/ms378878(v=sql.110).aspx), their JDBC driver should map both money types to a java bigdecimal…

So please check that it's PostgresSQL's numeric that is mapped to a BigNumber(it seems logical). If that's the case, we can try to map it to a numeric(6,4). This should do the trick.

The incremental mode has been seldom tested, by the way, most users do a one-shot migration… so that's why you find so many problems here, sorry about that :(

**Comment by JCallico** [comment]
I've had a patch ready since Monday but Kettle keeps crashing on me to the point that the whole Windows 10 PC becomes unresponsive and a hard reset is required.

**Comment by marco44** [comment]
That's weird. What you are describing sounds like a swap storm, so maybe you are just out of memory ?

Maybe JAVAXMEM is a bit high for your environment ? (depending on your machine). This memory limit is quite approximative, from what I have seen. I've seen up to 2 times JAVAXMEM used on my machines. But as I do this on large servers usually, I don't have problems.

There are other tuning options, such as reducing batch size, to lower memory requirements. The setup I'm proposing is more server-oriented.

**Comment by JCallico** [comment]
I have 32GB of RAM on my workstation :-)

I modified spoon.bat to use more memory for Java:
if "%PENTAHO_DI_JAVA_OPTIONS%"=="" set PENTAHO_DI_JAVA_OPTIONS="-Xms4096m" "-Xmx8192m" "-XX:MaxPermSize=1024m"

**Comment by JCallico** [comment]
Anyway, in my solution I modified the $types array to include the precision and scale like this:

`'smallmoney'       => 'numeric(6,4)',`

Are you OK with this or you rather leave the smallmoney to numeric mapping and add an special case in the convert_type subroutine?

**Comment by marco44** [comment]
No, if kettle is happy with numeric(6,4) and that avoids casting all over the place, I'm all for it :)

**Comment by marco44** [comment]
Never tried to run spoon in Windows, so I don't know how memory consumption is there. On Linux, I often saw Java use twice what I told it too.

**Comment by JCallico** [comment]
It seems to be working for both the migration and incremental scripts.
The money to numeric conversion seems to be working fine as well.
I'll do some more testing and the send you a pull request.
