### ISSUE TITLE
Error "Cannot understand this comment" should probably be a Warning

### ISSUE THREAD

**Issue by auspex** [dalibo/sqlserver2pgsql#67]
```
Cannot understand this comment: EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Records the user that issued the checkblock' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'data_entry_check_block', @level2type=N'CONSTRAINT',@level2name=N'FK_data_entry_check_block_issued_by'
 at sqlserver2pgsql/sqlserver2pgsql.pl line 2035, <$file> line 1508.
        main::parse_dump() called at sqlserver2pgsql/sqlserver2pgsql.pl line 2831
```

I'm not sure if this error would _always_ be issued only for this sort of thing (that is, extended properties should be able to be safely dropped), but when it says "Cannot understand this comment", I would think it should be safe to just issue a warning.  Alternatively, if the same message could be issued for things of import, perhaps it shouldn't say "comment"--perhaps _instruction_ would be a better wording.

**Comment by marco44** [comment]
Well, the thing is, as it dies when encountering the message, I get a bug report and can fix the issue (and check that I didn't ignore something important).

Can you provide me the few lines (or even better, the full sql dump), so that I can fix it ?

If you can only provide me the few lines, please don't destroy the linefeed, indentation…

You can send me the dump at cousinmarc at gmail dot com

**Comment by auspex** [comment]
Yeah, I'll get that to ASAP. I'm certain _I_ don't need this, so I'm just going to filter it out of my copy of the dump, but you can certainly have the original.
