### ISSUE TITLE
sqlserver2pgsql does not preserve case in table and column names

### ISSUE THREAD

**Issue by auspex** [dalibo/sqlserver2pgsql#69]
My SqlServer schema is a legacy hodgepodge with absolutely no naming standards. My app is dotNet with EntityFramework, so should be able to translate to using PgSql almost transparently.

Unfortunately the SQLServer table `[dbo].[Users]` becomes `"public"."users"`. And the usage information says *The `-keep_identifier_case` option is **"(not advised)"**.*

I think that is, itself, ill-advised.  In most cases, to seamlessly migrate a SqlServer application to PostGres, you will need to retain the case. Certainly, in my case, with a dotNet app, it's the only way to make things work without a lot of extra effort.

I'm not saying that it's not a good idea to keep identifiers in lower case, merely that it's generally a _better_ idea to not change case when applications already have an expectation.

**Comment by marco44** [comment]
It really depends on how your client application does the queries. If the objects names are protected (double quotes as the SQL standard specifies) you should keep the case. If objects are accessed in a case insensitive way (not protected in the SQL code, it's what I've mostly seen), you should transform everything to lowercase.

And anyway, if you migrate, maybe it's the occasion to cleanup and get rid of the camelcase nonsense (in a database, if it complies with sql standard, creating case sensitive objects name means you're adding a lot of not so useful double quotes all over the place). If you can't, then the -keep_identifier_case is for you.

**Comment by auspex** [comment]
You're rather missing the point. This is a tool designed for migrating SQL Server to PostGres. A great deal of SQL Server code is written using Entity Framework. The LAST thing you want to do when you migrate an EF application is change the case. It does all the quoting for you. So, no, I'm NOT adding any double quotes.

And no, it's never the time to "cleanup and get rid of the camelcase nonsense". You migrate, get your application working, _then_ you clean up the nonsense. I need this code to run against both PG & SQL server until I get _everything_ moved to PostGres.

**Comment by marco44** [comment]
Some applications are written using entity framework. Some are written using Hibernate or NHibernate. Some are written with plain queries. There are even masochists writing their own ORM. For any of those, if you don't have an option to "not protect" case, please go ahead and use camelcase. You'll just make anyone using the database directly (a dba for instance) miserable, but if you have no choice, the option is here.

This piece of code has already been used to migrate quite a few databases (hundreds). There were some (rare) cases where keeping the case was necessary… Because there was no setting to prevent quoting of identifiers, or the case of identifiers was forced all over the place in the client application. So yes, I'll stick with this "not advised", because 95% of the time, it was just a matter of not having to do anything to use a lower case schema, or at worst, changing one setting in an ORM, instead of going with a case sensitive schema and having to then alter all tables to change all columns names.

Your use case may be different. But it has been very rare until now.
